
import React, { createContext, useContext, useState, ReactNode } from 'react';

type Language = 'pt-BR' | 'en-US' | 'es-ES' | 'fr-FR' | 'de-DE';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const translations: Record<Language, Record<string, string>> = {
  'pt-BR': {
    'overview': 'Visão Geral',
    'market': 'Mercado',
    'portfolio': 'Portfólio',
    'wallet': 'Carteira',
    'team': 'Equipe',
    'exchange': 'Câmbio',
    'settings': 'Configurações',
    'admin': 'Administração',
    'logout': 'Sair da Conta',
    'profile': 'Meu Perfil',
    'security': 'Segurança',
    'preferences': 'Preferências',
    'delete_account': 'Excluir Minha Conta',
    'danger_zone': 'Zona de Perigo',
    'save_changes': 'Salvar Alterações',
    'theme_dark': 'Tema Escuro',
    'notifications': 'Notificações Push',
    'beta_features': 'Funcionalidades Beta',
    'beta_features_desc': 'Tenha acesso antecipado a novos recursos experimentais.',
    'beta_enabled': 'Funcionalidades Beta ativadas.',
    'beta_disabled': 'Funcionalidades Beta desativadas.',
    'language': 'Idioma',
    'change': 'Alterar',
    'active': 'Ativo',
    'search': 'Buscar ativos...',
    'welcome': 'Bem-vindo',
    'total_balance': 'Saldo Total',
    'deposit': 'Depositar',
    'withdraw': 'Sacar',
    'convert': 'Converter',
    'team_title': 'Sua Equipe',
    'team_subtitle': 'Gerencie seus indicados e acompanhe suas comissões.',
    'commission_balance': 'Saldo de Comissões',
    'total_affiliates': 'Total de Indicados',
    'rank': 'Rank Atual',
    'invite_friends': 'Convide Amigos',
    'referral_link': 'Seu Link de Afiliado',
    'notifications_title': 'Notificações',
    'notifications_subtitle': 'Acompanhe as atualizações importantes da sua conta.',
    'mark_all_read': 'Marcar tudo como lido',
    'no_notifications': 'Tudo limpo!',
    'notifications_empty_state': 'Você não tem novas notificações no momento.',
    'announcements_title': 'Comunicados',
    'announcements_subtitle': 'Fique por dentro das novidades e atualizações da plataforma.',
    'no_announcements': 'Nenhum comunicado.',
    'announcements_empty_state': 'Não há comunicados ativos no momento.',
    'support_title': 'Suporte',
    'support_subtitle': 'Como podemos ajudar você hoje?',
    'automated_support': 'Suporte Automatizado',
    'human_support': 'Atendimento Humano'
  },
  'en-US': {
    'overview': 'Overview',
    'market': 'Market',
    'portfolio': 'Portfolio',
    'wallet': 'Wallet',
    'team': 'Team',
    'exchange': 'Exchange',
    'settings': 'Settings',
    'admin': 'Administration',
    'logout': 'Logout',
    'profile': 'My Profile',
    'security': 'Security',
    'preferences': 'Preferences',
    'delete_account': 'Delete My Account',
    'danger_zone': 'Danger Zone',
    'save_changes': 'Save Changes',
    'theme_dark': 'Dark Theme',
    'notifications': 'Push Notifications',
    'beta_features': 'Beta Features',
    'beta_features_desc': 'Get early access to new experimental features.',
    'beta_enabled': 'Beta features enabled.',
    'beta_disabled': 'Beta features disabled.',
    'language': 'Language',
    'change': 'Change',
    'active': 'Active',
    'search': 'Search assets...',
    'welcome': 'Welcome',
    'total_balance': 'Total Balance',
    'deposit': 'Deposit',
    'withdraw': 'Withdraw',
    'convert': 'Convert',
    'team_title': 'Your Team',
    'team_subtitle': 'Manage your referrals and track your commissions.',
    'commission_balance': 'Commission Balance',
    'total_affiliates': 'Total Referrals',
    'rank': 'Current Rank',
    'invite_friends': 'Invite Friends',
    'referral_link': 'Your Referral Link',
    'notifications_title': 'Notifications',
    'notifications_subtitle': 'Track important updates about your account.',
    'mark_all_read': 'Mark all as read',
    'no_notifications': 'All clear!',
    'notifications_empty_state': 'You have no new notifications at the moment.',
    'announcements_title': 'Announcements',
    'announcements_subtitle': 'Stay updated with platform news and updates.',
    'no_announcements': 'No announcements.',
    'announcements_empty_state': 'There are no active announcements at the moment.',
    'support_title': 'Support',
    'support_subtitle': 'How can we help you today?',
    'automated_support': 'Automated Support',
    'human_support': 'Human Support'
  },
  'es-ES': {
    'overview': 'Visión General',
    'market': 'Mercado',
    'portfolio': 'Portafolio',
    'wallet': 'Billetera',
    'team': 'Equipo',
    'exchange': 'Intercambio',
    'settings': 'Configuración',
    'admin': 'Administración',
    'logout': 'Cerrar Sesión',
    'profile': 'Mi Perfil',
    'security': 'Seguridad',
    'preferences': 'Preferencias',
    'delete_account': 'Eliminar Cuenta',
    'danger_zone': 'Zona de Peligro',
    'save_changes': 'Guardar Cambios',
    'theme_dark': 'Tema Oscuro',
    'notifications': 'Notificaciones Push',
    'beta_features': 'Características Beta',
    'beta_features_desc': 'Obtenga acceso temprano a nuevas funciones experimentales.',
    'beta_enabled': 'Características Beta habilitadas.',
    'beta_disabled': 'Características Beta deshabilitadas.',
    'language': 'Idioma',
    'change': 'Cambiar',
    'active': 'Activo',
    'search': 'Buscar activos...',
    'welcome': 'Bienvenido',
    'total_balance': 'Saldo Total',
    'deposit': 'Depositar',
    'withdraw': 'Retirar',
    'convert': 'Convertir',
    'team_title': 'Tu Equipo',
    'team_subtitle': 'Gestiona tus referidos y sigue tus comisiones.',
    'commission_balance': 'Saldo de Comisiones',
    'total_affiliates': 'Total Referidos',
    'rank': 'Rango Actual',
    'invite_friends': 'Invitar Amigos',
    'referral_link': 'Tu Enlace de Referido',
    'notifications_title': 'Notificaciones',
    'notifications_subtitle': 'Sigue las actualizaciones importantes de tu cuenta.',
    'mark_all_read': 'Marcar todo como leído',
    'no_notifications': '¡Todo limpio!',
    'notifications_empty_state': 'No tienes nuevas notificaciones en este momento.',
    'announcements_title': 'Anuncios',
    'announcements_subtitle': 'Mantente al día con las novedades y actualizaciones de la plataforma.',
    'no_announcements': 'Sin anuncios.',
    'announcements_empty_state': 'No hay anuncios activos en este momento.',
    'support_title': 'Soporte',
    'support_subtitle': '¿Cómo podemos ayudarte hoy?',
    'automated_support': 'Soporte Automatizado',
    'human_support': 'Atención Humana'
  },
  'fr-FR': {
    'overview': 'Aperçu',
    'market': 'Marché',
    'portfolio': 'Portefeuille',
    'wallet': 'Portefeuille',
    'team': 'Équipe',
    'exchange': 'Échange',
    'settings': 'Paramètres',
    'admin': 'Administration',
    'logout': 'Se déconnecter',
    'profile': 'Mon Profil',
    'security': 'Sécurité',
    'preferences': 'Préférences',
    'delete_account': 'Supprimer le compte',
    'danger_zone': 'Zone de danger',
    'save_changes': 'Enregistrer',
    'theme_dark': 'Thème Sombre',
    'notifications': 'Notifications Push',
    'beta_features': 'Fonctionnalités Bêta',
    'beta_features_desc': 'Obtenez un accès anticipé aux nouvelles fonctionnalités expérimentales.',
    'beta_enabled': 'Fonctionnalités Bêta activées.',
    'beta_disabled': 'Fonctionnalités Bêta désactivées.',
    'language': 'Langue',
    'change': 'Changer',
    'active': 'Actif',
    'search': 'Rechercher...',
    'welcome': 'Bienvenue',
    'total_balance': 'Solde Total',
    'deposit': 'Dépôt',
    'withdraw': 'Retrait',
    'convert': 'Convertir',
    'team_title': 'Votre Équipe',
    'team_subtitle': 'Gérez vos parrainages et suivez vos commissions.',
    'commission_balance': 'Solde de Commission',
    'total_affiliates': 'Total Parrainages',
    'rank': 'Rang Actuel',
    'invite_friends': 'Inviter des Amis',
    'referral_link': 'Votre Lien de Parrainage',
    'notifications_title': 'Notifications',
    'notifications_subtitle': 'Suivez les mises à jour importantes de votre compte.',
    'mark_all_read': 'Tout marquer comme lu',
    'no_notifications': 'Tout est propre !',
    'notifications_empty_state': 'Vous n\'avez pas de nouvelles notifications pour le moment.',
    'announcements_title': 'Annonces',
    'announcements_subtitle': 'Restez informé des nouvelles et mises à jour de la plateforme.',
    'no_announcements': 'Aucune annonce.',
    'announcements_empty_state': 'Il n\'y a aucune annonce active pour le moment.',
    'support_title': 'Support',
    'support_subtitle': 'Comment pouvons-nous vous aider aujourd\'hui ?',
    'automated_support': 'Support Automatisé',
    'human_support': 'Support Humain'
  },
  'de-DE': {
    'overview': 'Übersicht',
    'market': 'Markt',
    'portfolio': 'Portfolio',
    'wallet': 'Brieftasche',
    'team': 'Team',
    'exchange': 'Austausch',
    'settings': 'Einstellungen',
    'admin': 'Verwaltung',
    'logout': 'Abmelden',
    'profile': 'Mein Profil',
    'security': 'Sicherheit',
    'preferences': 'Einstellungen',
    'delete_account': 'Konto löschen',
    'danger_zone': 'Gefahrenzone',
    'save_changes': 'Speichern',
    'theme_dark': 'Dunkles Design',
    'notifications': 'Push-Benachrichtigungen',
    'beta_features': 'Beta-Funktionen',
    'beta_features_desc': 'Erhalten Sie frühzeitigen Zugang zu neuen experimentellen Funktionen.',
    'beta_enabled': 'Beta-Funktionen aktiviert.',
    'beta_disabled': 'Beta-Funktionen deaktiviert.',
    'language': 'Sprache',
    'change': 'Ändern',
    'active': 'Aktiv',
    'search': 'Suchen...',
    'welcome': 'Willkommen',
    'total_balance': 'Gesamtsaldo',
    'deposit': 'Einzahlen',
    'withdraw': 'Abheben',
    'convert': 'Konvertieren',
    'team_title': 'Dein Team',
    'team_subtitle': 'Verwalte deine Empfehlungen und verfolge deine Provisionen.',
    'commission_balance': 'Provisionsguthaben',
    'total_affiliates': 'Gesamt Empfehlungen',
    'rank': 'Aktueller Rang',
    'invite_friends': 'Freunde Einladen',
    'referral_link': 'Dein Empfehlungslink',
    'notifications_title': 'Benachrichtigungen',
    'notifications_subtitle': 'Verfolge wichtige Updates zu deinem Konto.',
    'mark_all_read': 'Alle als gelesen markieren',
    'no_notifications': 'Alles sauber!',
    'notifications_empty_state': 'Du hast im Moment keine neuen Benachrichtigungen.',
    'announcements_title': 'Ankündigungen',
    'announcements_subtitle': 'Bleiben Sie auf dem Laufenden mit Plattform-Neuigkeiten und Updates.',
    'no_announcements': 'Keine Ankündigungen.',
    'announcements_empty_state': 'Derzeit gibt es keine aktiven Ankündigungen.',
    'support_title': 'Support',
    'support_subtitle': 'Wie können wir Ihnen heute helfen?',
    'automated_support': 'Automatisierter Support',
    'human_support': 'Menschlicher Support'
  }
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const LanguageProvider: React.FC<{ children: ReactNode }> = ({ children }) => {
  const [language, setLanguage] = useState<Language>('pt-BR');

  const t = (key: string) => {
    return translations[language][key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};
